spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDR}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        generate_statistics: true

logging:
  level:
    org:
      apache:
        http: DEBUG
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
      springframework:
        security: DEBUG
        web:
          client:
            RestTemplate: DEBUG

management:
  endpoint:
    health:
      show-details: always

setting:
  service:
    internal:
      name: 'Service bpm'
      key: INTERNAL_KEY

plugin.identity.keycloak:
  keycloakIssuerUrl: http://keycloak:8180/auth/realms/bpm
  keycloakAdminUrl: http://keycloak:8180/auth/admin/realms/bpm
  clientId: bpm-identity-service
  clientSecret: SECRET_VAL
  useEmailAsCamundaUserId: true
  administratorGroupName: bpm-admin

keycloak:
  auth-server-url: http://keycloak:8080/auth/
  realm: bpm
  resource: bpm-identity-service
  ssl-required: external
  credentials:
    secret: SECRET_VAL

