springdoc:
  version: '3.0'
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%-5level] [%-25thread] [%-36X{correlationId}] [%C{0}@%L]: %msg%n'

spring:
  main:
    banner-mode: off

server:
  error:
    include-message: always
  servlet:
    context-path: ${SERVICE_CONTEXT_PATH:/}

camunda.bpm:
  authorization:
    enabled: true

setting:
  service:
    internal:
      name: 'Service bpm'
      key: ${INTERNAL_SERVICE_KEY}

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
