CREATE TABLE IF NOT EXISTS surveyor_notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  surveyor_id VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL,
  notification_status VARCHAR(255) NOT NULL,
  read_status VARCHAR(255) NOT NULL,
  action_type VARCHAR(255) NOT NULL,
  notification_data TEXT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_user VARCHAR(255) DEFAULT 'system',
  updated_date TIMESTAMP NULL,
  updated_user VARCHAR(255)
);

DROP INDEX IF EXISTS idx_notification_status;
CREATE INDEX idx_notification_status ON surveyor_notification (notification_status);

DROP INDEX IF EXISTS idx_read_status;
CREATE INDEX idx_read_status ON surveyor_notification (read_status);

DROP INDEX IF EXISTS idx_action_type;
CREATE INDEX idx_action_type ON surveyor_notification (action_type);
