CREATE TABLE IF NOT EXISTS application (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  lead_id UUID NOT NULL,
  lead_number VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  collateral_id BIGINT NOT NULL,
  applicant_id BIGINT NOT NULL,
  amount NUMERIC(17, 2) NOT NULL,
  tenor INTEGER NOT NULL,
  installment_amount NUMERIC(17, 2) NOT NULL,
  product_id BIGINT NOT NULL,
  branch_id BIGINT NULL,
  process_id UUID NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_user VARCHAR(255) DEFAULT 'system',
  updated_date TIMESTAMP NULL,
  updated_user VARCHAR(255),
  CONSTRAINT fk_application_applicant_applicant_id FOREIGN KEY (applicant_id) REFERENCES applicant (id),
  CONSTRAINT fk_application_collateral_collateral_id FOREIGN KEY (collateral_id) REFERENCES collateral (id)
);

DROP INDEX IF EXISTS idx_application_process_id;
CREATE INDEX idx_application_process_id ON application (process_id);

DROP INDEX IF EXISTS idx_application_branch_id;
CREATE INDEX idx_application_branch_id ON application (branch_id);

DROP INDEX IF EXISTS idx_application_status;
CREATE INDEX idx_application_status ON application (status);
