CREATE TABLE IF NOT EXISTS operation_assignment_funding_information (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL,
  funding_amount DECIMAL NULL,
  tenor BIGINT NULL,
  installment_amount DECIMAL NULL,
  funding_method VARCHAR(255) NULL,
  bank_name VARCHAR(255) NULL,
  bank_account_number VARCHAR(255) NULL,
  bank_account_name VARCHAR(255) NULL,
  bank_account_status VARCHAR(255) NULL,
  effective_date VARCHAR(255) NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_user VARCHAR(255) DEFAULT 'system',
  updated_date TIMESTAMP NULL,
  updated_user VARCHAR(255),
  CONSTRAINT fk_operation_assignment_funding_information_operation_assignment_assignment_id FOREIGN KEY (assignment_id) REFERENCES operation_assignment (id)
);
