CREATE TABLE IF NOT EXISTS operation_assignment_document_sign (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL,
  bank_receipt_by_customer BOOLEAN DEFAULT FALSE,
  bank_receipt_by_owner BOOLEAN DEFAULT FALSE,
  customer_application_request BOOLEAN DEFAULT FALSE,
  loan_contract_agreement_transfer_title BOOLEAN DEFAULT FALSE,
  loan_control_agreement_funding BOOLEAN DEFAULT FALSE,
  fiduciary BOOLEAN DEFAULT FALSE,
  fpp_signed BOOLEAN DEFAULT FALSE,
  customer_sign_document_photo VARCHAR(255) NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_user VARCHAR(255) DEFAULT 'system',
  updated_date TIMESTAMP NULL,
  updated_user VARCHAR(255),
  CONSTRAINT fk_operation_assignment_document_sign_operation_assignment_assignment_id FOREIGN KEY (assignment_id) REFERENCES operation_assignment (id)
);
