CREATE TABLE IF NOT EXISTS collateral (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_code VARCHAR(255) NOT NULL,
  brand_name VARCHAR(255) NOT NULL,
  model_code VARCHAR(255) NOT NULL,
  model_name VARCHAR(255) NOT NULL,
  variant_code VARCHAR(255) NOT NULL,
  variant_name VARCHAR(255) NOT NULL,
  year_made INT NOT NULL,
  value_estimate NUMERIC(17,2) NOT NULL,
  license_number VARCHAR(255) NOT NULL,
  registration_number VARCHAR(255) NOT NULL,
  registration_photo VARCHAR(255) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_user VARCHAR(255) DEFAULT 'system',
  updated_date TIMESTAMP NULL,
  updated_user VARCHAR(255)
);

DROP INDEX IF EXISTS idx_collateral_brand_code;
CREATE INDEX idx_collateral_brand_code ON collateral (brand_code);

DROP INDEX IF EXISTS idx_collateral_model_code;
CREATE INDEX idx_collateral_model_code ON collateral (model_code);

DROP INDEX IF EXISTS idx_collateral_variant_code;
CREATE INDEX idx_collateral_variant_code ON collateral (variant_code);

DROP INDEX IF EXISTS idx_collateral_year_made;
CREATE INDEX idx_collateral_year_made ON collateral (year_made);
