CREATE TABLE IF NOT EXISTS surveyor_assignment_physical_document (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL,
  vehicle_owner_photo_one VARCHAR(255) NULL,
  vehicle_owner_photo_two VARCHAR(255) NULL,
  vehicle_owner_photo_three VARCHAR(255) NULL,
  vehicle_owner_photo_four VARCHAR(255) NULL,
  vehicle_ownership_identity_card_photo VARCHAR(255) NULL,
  additional_asset_registration_photo VARCHAR(255) NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_user VARCHAR(255) DEFAULT 'system',
  updated_date TIMESTAMP NULL,
  updated_user VARCHAR(255),
  CONSTRAINT fk_surveyor_assignment_physical_document_surveyor_assignment_assignment_id FOREIGN KEY (assignment_id) REFERENCES surveyor_assignment (id)
);
